spring:
  application:
    name: programmer-ground-chat-server

server:
  port: 8081
  error:
    whitelabel:
      enabled: false


message:
  web-socket-path: "/chat"
  message-subscribe-context-path: "/subscribe"
  message-publish-context-path: "/publish"

logging:
  level:
    org.springframework.messaging: trace

