server:
  port: 8080

---
spring:
  profiles: seansin-local
  # 자신의 환경에 맞게 active 하면됌.

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/db/programmer-ground
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      #naming:
      #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    restart:
      enabled: true

  security:
    jwt-token:
      secret-key: awdsd

    oauth2:
      client:
        registration:
          github:
            client-id: 5f8150b5b4b06259a3aa
            client-secret: 1fa30fbeceef904db5b2a1323b32dbcdd200379b
            scope: public_repo, read:user

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
---

---
spring:
  profiles:
    active: jaewoo-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    hibernate:
      #옵션 create, update, none, create-drop, validate 있음
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    jwt-token:
      secret-key: awdsd

    oauth2:
      client:
        registration:
          github:
            client-id: 5f8150b5b4b06259a3aa
            client-secret: 1fa30fbeceef904db5b2a1323b32dbcdd200379b
            scope: public_repo, read:user
---