---

spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: "common"
  security:
    jwt-token:
      secret-key: awdsd
    oauth2:
      client:
        registration:
          github:
            client-id: 5f8150b5b4b06259a3aa
            client-secret: 1fa30fbeceef904db5b2a1323b32dbcdd200379b
            scope: public_repo, read:user

server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
---

spring:
  profiles:
    group:
      "seansin-local": "seansin-localdb,common"

---

spring:
  profiles:
    group:
      "jeawoo-local": "jaewoo-localdb,common"

---

spring:
  profiles:
    group:
      "jinhyun-local": "jinhyun-localdb,common"

---

spring:
  config:
    activate:
      on-profile: "seansin-localdb"
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pg?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zxcv1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: "jaewoo-localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: awdsd123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
  config:
    activate:
      on-profile: "jinhyun-localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---