server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:programmer-ground/ProgrammerGround-Config.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKgIBAAKCAgEA2/SdSXtu+vExhWPUjsXbZHjk0nSzZIuW5nVVgFSEZCR+0Mgv
            IFPcXBXkFRoKAz10+bSVrZBWdn3CXxjkqG6qI1TkjOSvKE9w0G+2B+xPGHr/UVSy
            FecVwZ7tE+TP8Ya/BfDPOc8pAonNiw4ICE3MR/nq8SexHDWCg3NP5hYnb+fccv/L
            JeWC/sx5udHGPRJhHTmqYNArOrI3+I35cG0yPIjJSK+2rSaDWHLnNLwYr9S4/GVE
            +v5piBQzpAvug9m9srL2PP37dfNLCAlJ7gJGAvyPbfX6OtSInG/+Y63vnMAY1M8a
            pZT3uy3SPHkjIo0lv/bnyALe8aUJ2apfH5fltZRWLckxSJbdbkdL/2RhPGcDKVYT
            GQL1iZAu+RSQnjnXg59kq10gA9+jJDE9/6XTehMuU9nHca81agJric1+WqTOyxal
            TC9X5fCZxUDDfcdPQHfjFZAtnZy/0GrmAXG24qDb63FsDFNjnta5mwEAPwmQbCvl
            JKjE5OG9mVwrW184XUt9tTQM+XNlxM9PYs+C5SoGWlcxCdxIX0TzZSJ2fUo3onWu
            1I3rzF3UJlQVOeD7RPbr8W7YbMBwAiM6xX7S64GMKtmIHr3pXyhuG8k8u3tzs1dT
            Hu8wI54CxAFG32Vrzhtp6i6dgXRP0GCmkTGdKXCEM2ZKOWMj+l9JcXspIy8CAwEA
            AQKCAgEAp4uIOA4W9n29LA9kPTEHslvIaWtNrvwJgRjFfVBj3GhUVTL3eteGVnqy
            V0STde5daUwea6wzwGSBJ7EtlANgBDPJOG2F4t3IYG2Hqjdd9JbUXx513Os+jlNB
            4dJ8d00duye4oh9j7LQNZqvUgIbKYdVEGlgSuBsmhHzU0r3zYnGqYcro8sAF7ZLR
            8jKRn7mdUga3+rD3DOnuap2y8Omsx6GmOYDnVLOufzRfW7Mf1ufh1RhK2CntNyO0
            RnR0RekZb8KUgNcysaEWeVOiBfOjYukBVFB3QFLekNNaYpF+oNdO0uPDN3fm0KTR
            rRDVK596ruQjoB5XtpfxjeUSOl2ZMjJmDEB+/6eujfmy3Hrz85nYlaeDdfWVf5Gy
            JKTn+h9UC/d/Xn1jXZPbRPEPcAo/UqsVs295hzrEFBSc2mR4qDTn/miHN0sFgiSg
            ptnFm3qvPFr1SAW0PIV4bJG+ygIQgdu9UhcPjvrNVYjRn0YgZ9/ZW8YN50npIL1t
            A2EzynmXbKOhGWQWRxzWwDQsjhqxBeJx8Vbjlnj7/75UJIbRsKChX61SFS1QxAOO
            7spFWHJrvWQ/lGm1TYIXWMuDKfWQzM9g6iuZcQgY9+rr6c7KOqnqmCa2dWVZGuSA
            7ZPGFed+6N7ENWxcUvwK0FpYNhnSwQHjwroDslOeNTz0whWTDpECggEBAPtOHm8N
            lttQZfPZUCXvSxJr8p/K7VmKlqbEWghSumnSOC4uF/slsy0tDSeNAhsXCpjo3fWZ
            SJSN4OC6IiypaSkyWF+DGNnyc3IvKMdkMeVsl4O1I7eGDjrusMvnQZt1SRowzhvz
            JlqGTiKSxNgX734YYtOMOdf+NgCgO6dBR8DlWm2/7s1bqLpcPToOuIOSbuLH6f/I
            bjvo5B8l/3E02op5BLy14yXGrtqOSOrTPGJqy1ExdFzXRMM+gQbCr5xJG6o4AGfc
            hqZkgcVIKCm1/ow8HE0SdZtRYnCREV7WBBilFove1qcKciRsFALzS12W5CWuoYG6
            jQBRWcmM16tu9YcCggEBAOAQkGx0qo4O9brsde7mn+w/i9aJfrn/7LIOEpqujy1D
            nCFQzQdqjy6ROUwJbIvkpoVE611wikz4RKcLZIjKf75opHSNX6eQnBEPiz8j6rVd
            WtDhJXdCofu01jIvaUPbRiGvVfy41IZD5BWoGaRL33Fz7Pq9mHQ7c6mNkJYs9tEr
            f3viEQTqs/DTmN7H0z+XFiT9M0Gf9CPDRnr5vu09GvcoqzdV0hUTPK4CwwqaQa3I
            cGq24+73NOJah51G55G8bfCKOTM3lTuVvxX93y3OKj/cQMYGclhYKpPRPoKbeQrg
            PiuA+7OVypQHGOBMxmzra7lhx4DOpQ0dMh1O8kedzxkCggEAek2XhCaR76ReKeHu
            HrgpygpdJyVkg/ptvTW8N2bDsHKNwvPN2f2MCQVu7Hu0tahuEOLr+vYhm6K8+cG8
            lg3QzyrgVYOA2bkkNEL9TqTVn7lMt921R0DntgiqZGHkzRq0fBmahYG9fbr1VeAm
            CqEDflOx7RDGqfbfI0jYH1sm55r3eog5WRotsJzpc1Lsu6PNcXMnz8Mk2uVJ+FrO
            ybKWVWP2ST0gEidyu40ZsaciMSeWUaqG3hQqM/c8ZiTjwGTYIOxmTiXGJj6t5Wxr
            l3kqK+epQl0kfXWLOgtv776qebAGnAXUY7EywcUTrCfp2t9vo2Ms2O0IaEovL2br
            I1S6CwKCAQEAyAUBaFAdkQM5ycwc2091o+h2ZOYJAvG70pdNdFgv6DBayELhRKWT
            e/aYN5CSHa/YF1AW7CryyxM19gjtjk93CftQE9vAcE1fhLtjitH9TDoyQBU85OHO
            yGv+an54ceLlEFz9XcWBsvoYOlz9xvUUWqsp+gwWdGw+LDX7xJQPIVq7S1Pb7Y+3
            Yl0CMp4frrypQAvoHcU0pFhGKrGYByBtWgYsEhHCoJ2zpYNBqc1apFAySpFJmKGF
            zCsUtQn+3tJfMkOyHE6aIb7j/jXLbZCFlsx/5kcK/GJ4X8yDCQTRYSwdU6ipCP/G
            /632PwVKfSEL4UmwVwQhwzs06YT4M4ZkwQKCAQEAtEgYI4YEnSz3AimWMPVN3PAY
            hZHCuL179vryzWCUY/yqx0/wz/OLy/nnk0yzfoKpE38V8+10t55HiIQAeo54I8z7
            lXPezqyBsdc6XQKDNwSGIn7IOPR8w2KYAf6xTBmwg5rECvJPXzqiXJvNLMXjwMKb
            AQB8QE4G8aF7r0GsPsULmjBJKk9s2F8gnhDZp6t3ijEobnvyX3CoIxgjvXUuoVNa
            6NFWS7ZFHcd4NnisIsI6+5tL+OjuhXYmcTzPl1qX8WNXnrPdPCHXIap6vjHXg7kN
            gAv+Uzxe3N2DFE5Ebhx2joMw00pTjVKDme3K/NX1guO4YForGzEIlr7KASU9IA==
            -----END RSA PRIVATE KEY-----