server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
spring:
  management:
    endpoint:
      web:
        exposure:
          include: refresh, health, beans
file:
  dir: src/main/resource/images/
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/