# 공통 프로파일
spring:
  config:
    activate:
      on-profile: "common"
  security:
    jwt-token:
      secret-key: awdsd

github:
  token: "bearer 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"
  org-url : "https://api.github.com/orgs/programmer-ground"
  org-repo-url : "https://api.github.com/repos/programmer-ground"

server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

---

spring:
  profiles:
    group:
      "seansin-local": "seansin-localdb,common"

---

spring:
  profiles:
    group:
      "jeawoo-local": "jeawoo-localdb,common"

---

spring:
  profiles:
    group:
      "jinhyun-local": "jinhyun-localdb,common"

---

spring:
  config:
    activate:
      on-profile: "seansin-localdb"
  datasource:
    url: jdbc:mariadb://localhost:3306/pg?serverTimezone=UTC&characterEncoding=UTF-8
    username: seansin
    password: zxcv123
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    restart:
      enabled: true

# TODO : CDN이나 S3로 변경할 예정
# TODO : addResourceHandlers 통해서 해결하게 바꿔야함
file:
  dir: /Users/seansin/images
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/

---

spring:
  config:
    activate:
      on-profile: "jeawoo-localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: awdsd123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show-sql: true

file:
  dir: /Users/jaewoochoi/Desktop/image
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/

---


spring:
  config:
    activate:
      on-profile: "jinhyun-localdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show-sql: true

file:
  dir: /Users/jaewoochoi/Desktop/image
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/

---