---
spring:
  profiles:
    active: backend-h2db-local

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/db/programmer-ground
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    restart:
      enabled: true

  security:
    jwt-token:
      secret-key: awdsd

  #logging:
  #  level
  #    org.hibernate.SQL: debug
  #    org.hibernate.type: trace

server:
  port: 9000
---

---
spring:
  profiles: backend-mysql-dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: awdsd123
  jpa:
    hibernate:
      #옵션 create, update, none, create-drop, validate 있음
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    # MYSQL 방언 매핑 (MYSQL 5.x 이상)
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    jwt-token:
      secret-key: awdsd

server:
  port: 9000
---