---
# Suung Profile YAML
spring:
  profiles: seansin-local
    # 자신의 환경에 맞게 active 하면됌.

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/db/programmer-ground
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    restart:
      enabled: true

  security:
    jwt-token:
      secret-key: awdsd

github:
  token: "bearer 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"
  org-url : "https://api.github.com/orgs/programmer-ground"
  org-repo-url : "https://api.github.com/repos/programmer-ground"

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  #logging:
  #  level
  #    org.hibernate.SQL: debug
  #    org.hibernate.type: trace

server:
  port: 8080

#이미지 파일 저장 경로 설정 각자 컴퓨터에 맞게 설정
file:
  dir: /Users/jaewoochoi/Desktop/image
  playground-main-img: /pgmainimg/ #image/pgmainimg 만들 것
  playground-description-img: /pgdesimg/  #image/pgdesimg 만들 것
---

---
# Jeawoo Profile YAML
spring:
  profiles:
    active: jeawoo-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      #옵션 create, update, none, create-drop, validate 있음
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  security:
    jwt-token:
      secret-key: awdsd

server:
  port: 9000

file:
  dir: /Users/jaewoochoi/Desktop/image
  playground-main-img: /pgmainimg/
  playground-description-img: /pgdesimg/

---